# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/nginx
  tag: 1.27
  pullPolicy: IfNotPresent

gitSync:
  image:
    repository: docker.io/openweb/git-sync
    tag: 0.0.1
    pullPolicy: IfNotPresent
  env:
    GIT_SYNC_REPO: https://github.com/AGou-ops/AGou-ops.github.io.git
    GIT_SYNC_BRANCH: gh-pages
    GIT_SYNC_DEST: /git
    GIT_SYNC_REV: FETCH_HEAD
    GIT_SYNC_WAIT: "10"

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /
  hosts:
    - blog.rn.agou-ops.cn
  tls:
   - secretName: myblog-tls
     hosts:
       - blog.rn.agou-ops.cn

persistence:
  enableStatefulSetAutoDeletePVC: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: "local-path"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
