apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "myblog.fullname" . }}-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "myblog.name" . }}
    chart: {{ template "myblog.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
