name: PUSH_TO_COS
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    # hugo build static files
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.75.1'
        extended: true
    - name: Build
      run: hugo --minify
    # push to Tencent COS
    - uses: TencentCloud/cos-action@v1
      with:
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        # cos_bucket: ${{ secrets.COS_BUCKET }}
        # cos_region: ${{ secrets.COS_REGION }}
        cos_bucket: "agou-ops-1259153413"
        cos_region: "ap-chengdu"
        local_path: public
        remote_path: /
        clean: true
